apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app
          image: "lachisenarath576259/chat-app"
          ports:
            - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: chat-app
  namespace: webapps
spec:
  selector:
    app: chat-app
  ports:
    - name: http
      targetPort: 3001
      port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recieve-app
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recieve-app
  template:
    metadata:
      labels:
        app: recieve-app
    spec:
      containers:
        - name: recieve-app
          image: "lachisenarath576259/recieve-app"
          ports:
            - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: recieve-app
  namespace: webapps
spec:
  selector:
    app: recieve-app
  ports:
    - name: http
      targetPort: 3002
      port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: "lachisenarath576259/gateway"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: webapps
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - name: http
      targetPort: 3000
      port: 80
